import { Perfume, Collection } from "./types";

export const collections: Collection[] = [
  {
    id: "lattafa",
    name: "Lattafa",
    logo: "/lattafa/logo.png",
  },
  {
    id: "armaf",
    name: "Armaf",
    logo: "/armaf/logo.png",
  },
  {
    id: "swiss-arabian",
    name: "Swiss Arabian",
    logo: "/swiss-arabian/logo.png",
  },
  {
    id: "french-avenue",
    name: "French Avenue",
    logo: "/frence-avenue/logo.png",
  },
  {
    id: "emper",
    name: "Emper",
    logo: "/emper/logo.png",
  },
  {
    id: "camara-perfumes",
    name: "Camara Perfumes",
    logo: "/camara/logo.png",
  },
];

export const perfumes: Perfume[] = [
  // Lattafa Collection (9 products)
  {
    id: 1,
    name: "Yara Tous",
    collection: "lattafa",
    description:
      "Un aroma intenso y misterioso con notas de vainilla y pachulí.",
    price: 38,
    image: "/lattafa/yara-tous.png",
    gender: "Mujer",
    featured: true,
    rating: 4.8,
    notes: ["Vainilla", "Pachulí", "Ámbar"],
  },
  {
    id: 2,
    name: "Yara",
    collection: "lattafa",
    description:
      "Fragancia oriental con rosas del desierto y especias exóticas.",
    price: 38,
    image: "/lattafa/yara.png",
    gender: "Mujer",
    featured: false,
    rating: 4.6,
    notes: ["Rosa", "Azafrán", "Oud"],
  },
  {
    id: 3,
    name: "Yara Moi",
    collection: "lattafa",
    description: "Aroma cálido y envolvente inspirado en las dunas doradas.",
    price: 38,
    image: "/lattafa/yara-moi.png",
    gender: "Mujer",
    featured: true,
    rating: 4.7,
    notes: ["Ámbar", "Sándalo", "Incienso"],
  },
  {
    id: 4,
    name: "Yara Candy",
    collection: "lattafa",
    description: "Suave y elegante con notas de terciopelo y flores nocturnas.",
    price: 40,
    image: "/lattafa/yara-candy.png",
    gender: "Mujer",
    featured: false,
    rating: 4.5,
    notes: ["Jazmín", "Vainilla", "Almizcle"],
  },
  {
    id: 5,
    name: "Asad Bourbon",
    collection: "lattafa",
    description: "Majestuoso oud con toques de rosa y especias orientales.",
    price: 42,
    image: "/lattafa/asad-bourbon.png",
    gender: "Hombre",
    featured: true,
    rating: 4.9,
    notes: ["Oud", "Rosa", "Cardamomo"],
  },
  {
    id: 6,
    name: "Asad",
    collection: "lattafa",
    description: "Romántica fragancia nocturna con flores blancas y almizcle.",
    price: 38,
    image: "/lattafa/asad.png",
    gender: "Hombre",
    featured: false,
    rating: 4.4,
    notes: ["Gardenia", "Almizcle", "Cedro"],
  },
  {
    id: 7,
    name: "Ameerat Al Arab",
    collection: "lattafa",
    description: "Vibrante mezcla de especias orientales y maderas preciosas.",
    price: 34,
    image: "/lattafa/ameerat-al-arab.png",
    gender: "Mujer",
    featured: false,
    rating: 4.6,
    notes: ["Canela", "Clavo", "Sándalo"],
  },
  {
    id: 8,
    name: "Asad Zanzibar",
    collection: "lattafa",
    description: "Cálido y sensual con ámbar profundo y vainilla cremosa.",
    price: 38,
    image: "/lattafa/asad-zanzibar.png",
    gender: "Hombre",
    featured: false,
    rating: 4.7,
    notes: ["Ámbar", "Vainilla", "Benjuí"],
  },
  {
    id: 9,
    name: "Prive Rose",
    collection: "lattafa",
    description:
      "Exótica fragancia inspirada en las rutas comerciales antiguas.",
    price: 34,
    image: "/lattafa/prive-rose.png",
    gender: "Mujer",
    featured: false,
    rating: 4.5,
    notes: ["Bergamota", "Oud", "Pachulí"],
  },

  // Armaf Collection (6 products)
  {
    id: 10,
    name: "Tag Femme",
    collection: "armaf",
    description: "Frescura marina con toques cítricos y madera de cedro.",
    price: 42,
    image: "/armaf/tag-femme.png",
    gender: "Mujer",
    featured: true,
    rating: 4.7,
    notes: ["Bergamota", "Cedro", "Sal Marina"],
  },
  {
    id: 11,
    name: "Lionheart Men",
    collection: "armaf",
    description: "Intenso aroma a cuero con toques de especias y madera.",
    price: 57,
    image: "/armaf/lionheart-men.png",
    gender: "Hombre",
    featured: false,
    rating: 4.8,
    notes: ["Cuero", "Cardamomo", "Vetiver"],
  },
  {
    id: 12,
    name: "Lionheart Woman",
    collection: "armaf",
    description: "Refrescante como una cascada cristalina en primavera.",
    price: 57,
    image: "/armaf/lionheart-woman.png",
    gender: "Mujer",
    featured: false,
    rating: 4.6,
    notes: ["Agua", "Lirio", "Musgo"],
  },
  {
    id: 13,
    name: "Club de Nuit Women",
    collection: "armaf",
    description: "Poderoso y magnético como una tormenta nocturna.",
    price: 50,
    image: "/armaf/club-de-nuit-women.png",
    gender: "Mujer",
    featured: true,
    rating: 4.8,
    notes: ["Ozono", "Vetiver", "Ámbar Gris"],
  },
  {
    id: 14,
    name: "Club de Nuit Sillage",
    collection: "armaf",
    description: "Elegante y etéreo con notas plateadas y florales.",
    price: 57,
    image: "/armaf/club-de-nuit-sillage.png",
    gender: "Unisex",
    featured: false,
    rating: 4.5,
    notes: ["Iris", "Almizcle Blanco", "Cedro"],
  },
  {
    id: 15,
    name: "Club Nuit Iconic",
    collection: "armaf",
    description: "Explosivo y dinámico con energía masculina intensa.",
    price: 57,
    image: "/armaf/club-nuit-iconic.png",
    gender: "Hombre",
    featured: false,
    rating: 4.7,
    notes: ["Pimienta", "Tabaco", "Cuero"],
  },

  // Swiss Arabian Collection (6 products)
  {
    id: 16,
    name: "Casablanca",
    collection: "swiss-arabian",
    description: "Elegante composición floral con rosa damascena y jazmín.",
    price: 50,
    image: "/swiss-arabian/casablanca.png",
    gender: "Unisex",
    featured: true,
    rating: 4.9,
    notes: ["Rosa Damascena", "Jazmín", "Almizcle"],
  },
  {
    id: 17,
    name: "Saghaf Vanille Toffe",
    collection: "swiss-arabian",
    description: "Fresco como la brisa de los Alpes suizos al amanecer.",
    price: 57,
    image: "/swiss-arabian/saghaf-vanille-toffe.png",
    gender: "Unisex",
    featured: false,
    rating: 4.6,
    notes: ["Menta", "Eucalipto", "Cedro Blanco"],
  },
  {
    id: 18,
    name: "Shaghaf Oud",
    collection: "swiss-arabian",
    description: "Opulento y rico como los valles dorados de Suiza.",
    price: 54,
    image: "/swiss-arabian/shaghaf-oud.png",
    gender: "Unisex",
    featured: true,
    rating: 4.8,
    notes: ["Oud", "Miel", "Sándalo"],
  },
  {
    id: 19,
    name: "Saghaf Azraq",
    collection: "swiss-arabian",
    description: "Puro y cristalino como las cumbres nevadas.",
    price: 54,
    image: "/swiss-arabian/saghaf-azraq.png",
    gender: "Hombre",
    featured: false,
    rating: 4.7,
    notes: ["Bergamota", "Lirio", "Almizcle Blanco"],
  },
  {
    id: 20,
    name: "Shaghaf Tonka",
    collection: "swiss-arabian",
    description: "Verde y vibrante como los bosques esmeralda alpinos.",
    price: 54,
    image: "/swiss-arabian/shaghaf-tonka.png",
    gender: "Unisex",
    featured: false,
    rating: 4.5,
    notes: ["Pino", "Musgo", "Vetiver"],
  },
  {
    id: 21,
    name: "Shaghaf Ahmar",
    collection: "swiss-arabian",
    description: "Lujoso y sofisticado con terciopelo y especias preciosas.",
    price: 54,
    image: "/swiss-arabian/shaghaf-ahmar.png",
    gender: "Unisex",
    featured: true,
    rating: 4.9,
    notes: ["Rosa", "Azafrán", "Oud"],
  },

  // French Avenue Collection (6 products)
  {
    id: 22,
    name: "Pinnace",
    collection: "french-avenue",
    description: "Intenso y masculino con notas amaderadas y especiadas.",
    price: 49,
    image: "/frence-avenue/pinnace.png",
    gender: "Hombre",
    featured: false,
    rating: 4.6,
    notes: ["Sándalo", "Pimienta Negra", "Oud"],
  },
  {
    id: 23,
    name: "Coconut Leche",
    collection: "french-avenue",
    description: "Elegante como un paseo por los Campos Elíseos.",
    price: 47,
    image: "/frence-avenue/coconut-leche.png",
    gender: "Unisex",
    featured: true,
    rating: 4.8,
    notes: ["Rosa", "Peonía", "Almizcle"],
  },
  {
    id: 24,
    name: "Diwani Cairo",
    collection: "french-avenue",
    description: "Misterioso y seductor con profundidad francesa.",
    price: 51,
    image: "/frence-avenue/diwani-cairo.png",
    gender: "Unisex",
    featured: false,
    rating: 4.7,
    notes: ["Bergamota", "Lavanda", "Vetiver"],
  },
  {
    id: 25,
    name: "Azure Aoud",
    collection: "french-avenue",
    description: "Romántica y nostálgica como la Belle Époque parisina.",
    price: 49,
    image: "/frence-avenue/azure-aoud.png",
    gender: "Unisex",
    featured: true,
    rating: 4.9,
    notes: ["Violeta", "Iris", "Vainilla"],
  },
  {
    id: 26,
    name: "Royal Blend Noir",
    collection: "french-avenue",
    description: "Soñador como un atardecer en la Riviera francesa.",
    price: 51,
    image: "/frence-avenue/roayl-blend-noir.png",
    gender: "Hombre",
    featured: false,
    rating: 4.5,
    notes: ["Limón", "Lavanda", "Cedro"],
  },
  {
    id: 27,
    name: "Royal Blend",
    collection: "french-avenue",
    description: "Majestuoso y noble como un château real francés.",
    price: 51,
    image: "/frence-avenue/royal-blend.png",
    gender: "Unisex",
    featured: true,
    rating: 4.8,
    notes: ["Oud", "Rosa", "Ámbar"],
  },

  // Emper Collection (6 products)
  {
    id: 28,
    name: "Espada Prime",
    collection: "emper",
    description: "Radiante y luminoso con flores blancas y toques cítricos.",
    price: 37,
    image: "/emper/espada-prime.png",
    gender: "Hombre",
    featured: false,
    rating: 4.7,
    notes: ["Neroli", "Flor de Azahar", "Mandarina"],
  },
  {
    id: 29,
    name: "Espada Oro",
    collection: "emper",
    description: "Imperial y dorado como un imperio en su esplendor.",
    price: 37,
    image: "/emper/espada-oro.png",
    gender: "Hombre",
    featured: false,
    rating: 4.6,
    notes: ["Bergamota", "Ámbar", "Sándalo"],
  },
  {
    id: 30,
    name: "Desert Angel Blue Night",
    collection: "emper",
    description: "Elegante y cristalino con sofisticación moderna.",
    price: 40,
    image: "/emper/desert-angel-blue-nigt.png",
    gender: "Mujer",
    featured: true,
    rating: 4.8,
    notes: ["Peonía", "Almizcle", "Cedro"],
  },
  {
    id: 31,
    name: "Desert Angel Romance",
    collection: "emper",
    description: "Poderoso y real como el trueno de una tormenta imperial.",
    price: 40,
    image: "/emper/desert-angel-romance.png",
    gender: "Mujer",
    featured: false,
    rating: 4.7,
    notes: ["Vetiver", "Tabaco", "Ámbar"],
  },
  {
    id: 32,
    name: "Desert Angel",
    collection: "emper",
    description: "Suave como la seda con flores delicadas y frescas.",
    price: 40,
    image: "/emper/desert-angel.png",
    gender: "Mujer",
    featured: false,
    rating: 4.5,
    notes: ["Cerezo", "Peonía", "Almizcle Blanco"],
  },
  {
    id: 33,
    name: "Burj Dubai Arina",
    collection: "emper",
    description: "Coronado por la elegancia de la medianoche.",
    price: 37,
    image: "/emper/burj-dubai-arina.png",
    gender: "Mujer",
    featured: true,
    rating: 4.8,
    notes: ["Oud", "Rosa Negra", "Ámbar"],
  },

  // Camara Perfumes Collection (7 products)
  {
    id: 34,
    name: "Malaki Secret",
    collection: "camara-perfumes",
    description: "Opulento y cálido con ámbar, vainilla y especias exóticas.",
    price: 38.5,
    image: "/camara/malaki-secret.png",
    gender: "Hombre",
    featured: true,
    rating: 4.9,
    notes: ["Ámbar", "Vainilla", "Canela"],
  },
  {
    id: 35,
    name: "Ikhtiyari",
    collection: "camara-perfumes",
    description: "Espejismo del desierto con notas orientales cautivadoras.",
    price: 36.5,
    image: "/camara/ikhtiyari.png",
    gender: "Unisex",
    featured: false,
    rating: 4.7,
    notes: ["Oud", "Rosa", "Incienso"],
  },
  {
    id: 36,
    name: "Sahr Al Kalimat",
    collection: "camara-perfumes",
    description: "Oasis dorado en el desierto con frescura y calidez.",
    price: 38.5,
    image: "/camara/sahr-al-kalimat.png",
    gender: "Unisex",
    featured: true,
    rating: 4.8,
    notes: ["Jazmín", "Ámbar", "Sándalo"],
  },
  {
    id: 37,
    name: "Ghubar Al Dhahab",
    collection: "camara-perfumes",
    description: "Noches de terciopelo con elegancia y misterio.",
    price: 36.5,
    image: "/camara/ghubar-al-dhahab.png",
    gender: "Unisex",
    featured: false,
    rating: 4.6,
    notes: ["Oud", "Cuero", "Especias"],
  },
  {
    id: 38,
    name: "Dome Casabella",
    collection: "camara-perfumes",
    description: "Esencia perlada con pureza y sofisticación marina.",
    price: 37.5,
    image: "/camara/dome-casabella.png",
    gender: "Unisex",
    featured: false,
    rating: 4.5,
    notes: ["Perla", "Lirio", "Almizcle"],
  },
  {
    id: 39,
    name: "Angel Paradise",
    collection: "camara-perfumes",
    description: "Azafrán real con lujo y opulencia oriental.",
    price: 39.5,
    image: "/camara/angel-paradise.png",
    gender: "Mujer",
    featured: true,
    rating: 4.9,
    notes: ["Azafrán", "Oud", "Rosa"],
  },
  {
    id: 40,
    name: "Oxana Black",
    collection: "camara-perfumes",
    description: "Jardín místico con flores exóticas y maderas preciosas.",
    price: 37.5,
    image: "/camara/oxana-black.png",
    gender: "Mujer",
    featured: false,
    rating: 4.7,
    notes: ["Gardenia", "Sándalo", "Vainilla"],
  },
];
